### ISSUE TITLE
Embedding Org variable setup in the file

### ISSUE THREAD

**Issue by mmauger** [jessekelly881/Theme-Imagine#1]
Because Org is in Emacs you can use Emacs conventions to add Emacs file variable config to the tail end of your org document:

    * COMMENT Emacs local config
    # Local Variables:
    # org-html-htmlize-output-type: css
    # End:

The COMMENT market keeps the section from being exported, but Emacs still sees it.

**Comment by jessekelly881** [comment]
Oh! Amazing. Thank you. I will definitely add that.
